using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[Preserve]
public partial class BG_D3_MPCValve_AASTable : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4748224809407083938UL,17307079893483839678UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_id
	{
		get => _f_id[Index];
		set => _f_id[Index] = value;
	}
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public System.String f_subname
	{
		get => _f_subname[Index];
		set => _f_subname[Index] = value;
	}
	public System.String f_requestUrl => _f_requestUrl[Index];
	public List<BG_D3_UIField> f_response => BGCodeGenUtils.GetNested<BG_D3_UIField>(_f_response, Index);
	/**<summary><![CDATA[
	실 AAS 주소
	]]></summary>*/
	public System.String f_machineUrl
	{
		get => _f_machineUrl[Index];
		set => _f_machineUrl[Index] = value;
	}
	public List<BG_D3_MachField> f_machine => BGCodeGenUtils.GetNested<BG_D3_MachField>(_f_machine, Index);
	/**<summary><![CDATA[
	mainAreaSO
	]]></summary>*/
	public UnityEngine.ScriptableObject f_mainSO => _f_mainSO[Index];
	public System.Boolean f_IsOP
	{
		get => _f_IsOP[Index];
		set => _f_IsOP[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_id;
	public static BansheeGz.BGDatabase.BGFieldString _f_id => _ufle12jhs77_f_id ?? (_ufle12jhs77_f_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5400969442205441662UL, 2863042465284278156UL), () => _ufle12jhs77_f_id = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5389909768365081643UL, 10278790541875417216UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_subname;
	public static BansheeGz.BGDatabase.BGFieldString _f_subname => _ufle12jhs77_f_subname ?? (_ufle12jhs77_f_subname = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5525293451568216541UL, 5332012170899383467UL), () => _ufle12jhs77_f_subname = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_requestUrl;
	public static BansheeGz.BGDatabase.BGFieldString _f_requestUrl => _ufle12jhs77_f_requestUrl ?? (_ufle12jhs77_f_requestUrl = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5604501679004377788UL, 17579172908332752280UL), () => _ufle12jhs77_f_requestUrl = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_response;
	public static BansheeGz.BGDatabase.BGFieldNested _f_response => _ufle12jhs77_f_response ?? (_ufle12jhs77_f_response = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(4661421868839251965UL, 169893143722728373UL), () => _ufle12jhs77_f_response = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_machineUrl;
	public static BansheeGz.BGDatabase.BGFieldString _f_machineUrl => _ufle12jhs77_f_machineUrl ?? (_ufle12jhs77_f_machineUrl = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5344411596409658026UL, 11608987549991465098UL), () => _ufle12jhs77_f_machineUrl = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_machine;
	public static BansheeGz.BGDatabase.BGFieldNested _f_machine => _ufle12jhs77_f_machine ?? (_ufle12jhs77_f_machine = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5762697447553595170UL, 1265433579800857987UL), () => _ufle12jhs77_f_machine = null));
	private static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _ufle12jhs77_f_mainSO;
	public static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _f_mainSO => _ufle12jhs77_f_mainSO ?? (_ufle12jhs77_f_mainSO = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityScriptableObject>(MetaDefault, new BGId(5085342382525351471UL, 18292126605268939699UL), () => _ufle12jhs77_f_mainSO = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_IsOP;
	public static BansheeGz.BGDatabase.BGFieldBool _f_IsOP => _ufle12jhs77_f_IsOP ?? (_ufle12jhs77_f_IsOP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5505872605487458651UL, 6972216717418704829UL), () => _ufle12jhs77_f_IsOP = null));
	private BG_D3_MPCValve_AASTable() : base(MetaDefault) {}
	private BG_D3_MPCValve_AASTable(BGId id) : base(MetaDefault, id) {}
	private BG_D3_MPCValve_AASTable(BGMetaEntity meta) : base(meta) {}
	private BG_D3_MPCValve_AASTable(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static BG_D3_MPCValve_AASTable FindEntity(Predicate<BG_D3_MPCValve_AASTable> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<BG_D3_MPCValve_AASTable> FindEntities(Predicate<BG_D3_MPCValve_AASTable> filter, List<BG_D3_MPCValve_AASTable> result=null, Comparison<BG_D3_MPCValve_AASTable> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BG_D3_MPCValve_AASTable> action, Predicate<BG_D3_MPCValve_AASTable> filter=null, Comparison<BG_D3_MPCValve_AASTable> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static BG_D3_MPCValve_AASTable GetEntity(BGId entityId) => (BG_D3_MPCValve_AASTable) MetaDefault.GetEntity(entityId);
	public static BG_D3_MPCValve_AASTable GetEntity(int index) => (BG_D3_MPCValve_AASTable) MetaDefault[index];
	public static BG_D3_MPCValve_AASTable GetEntity(string entityName) => (BG_D3_MPCValve_AASTable) MetaDefault.GetEntity(entityName);
	public static BG_D3_MPCValve_AASTable NewEntity() => (BG_D3_MPCValve_AASTable) MetaDefault.NewEntity();
	public static BG_D3_MPCValve_AASTable NewEntity(BGId entityId) => (BG_D3_MPCValve_AASTable) MetaDefault.NewEntity(entityId);
	public static BG_D3_MPCValve_AASTable NewEntity(Action<BG_D3_MPCValve_AASTable> callback) => (BG_D3_MPCValve_AASTable) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BG_D3_MPCValve_AASTable)entity)));
	public List<BG_D3_UIField> Fillf_response(List<BG_D3_UIField> result) => BGCodeGenUtils.GetNested<BG_D3_UIField>(_f_response, Index, result);
	public List<BG_D3_MachField> Fillf_machine(List<BG_D3_MachField> result) => BGCodeGenUtils.GetNested<BG_D3_MachField>(_f_machine, Index, result);
	public UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<UnityEngine.ScriptableObject>? Loadf_mainSOAsync(Action<UnityEngine.ScriptableObject> completedCallback) => BGAddressablesCodeGenUtils.LoadAsync(_f_mainSO, Index, completedCallback);
	public string Getf_mainSOAddressablesAddress() => _f_mainSO.GetAddressablesAddress(Index);

	[Preserve]
	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_D3_MPCValve_AASTable(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_D3_MPCValve_AASTable(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "D3_MPCValve_AASTable";
		public const string id = "id";
		public const string name = "name";
		public const string subname = "subname";
		public const string requestUrl = "requestUrl";
		public const string response = "response";
		public const string machineUrl = "machineUrl";
		public const string machine = "machine";
		public const string mainSO = "mainSO";
		public const string IsOP = "IsOP";
	}
}

[Preserve]
public partial class BG_D3_UIField : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4974519446337498990UL,17173487470235527850UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name => _f_name[Index];
	public BG_D3_MPCValve_AASTable f_parent => (BG_D3_MPCValve_AASTable) _f_parent[Index];
	/**<summary><![CDATA[
	SPEC 하한치
	]]></summary>*/
	public System.String f_var1
	{
		get => _f_var1[Index];
		set => _f_var1[Index] = value;
	}
	/**<summary><![CDATA[
	Value
	]]></summary>*/
	public System.String f_var2
	{
		get => _f_var2[Index];
		set => _f_var2[Index] = value;
	}
	/**<summary><![CDATA[
	SPEC 상한치
	]]></summary>*/
	public System.String f_var3
	{
		get => _f_var3[Index];
		set => _f_var3[Index] = value;
	}
	/**<summary><![CDATA[
	네트워크 Response ID
	]]></summary>*/
	public System.String f_var4
	{
		get => _f_var4[Index];
		set => _f_var4[Index] = value;
	}
	public System.String f_var5
	{
		get => _f_var5[Index];
		set => _f_var5[Index] = value;
	}
	/**<summary><![CDATA[
	WebView 용도
	]]></summary>*/
	public System.String f_subUrl => _f_subUrl[Index];
	public System.Boolean f_isGroupTask
	{
		get => _f_isGroupTask[Index];
		set => _f_isGroupTask[Index] = value;
	}
	public System.String f_GroupTaskID
	{
		get => _f_GroupTaskID[Index];
		set => _f_GroupTaskID[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5109118155136028923UL, 11510207142725023374UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_parent;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_parent => _ufle12jhs77_f_parent ?? (_ufle12jhs77_f_parent = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4984180158753865745UL, 11699392582431059358UL), () => _ufle12jhs77_f_parent = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var1;
	public static BansheeGz.BGDatabase.BGFieldString _f_var1 => _ufle12jhs77_f_var1 ?? (_ufle12jhs77_f_var1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4906741384634690086UL, 2408512823393018535UL), () => _ufle12jhs77_f_var1 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var2;
	public static BansheeGz.BGDatabase.BGFieldString _f_var2 => _ufle12jhs77_f_var2 ?? (_ufle12jhs77_f_var2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5397138594993727201UL, 2510807910546460336UL), () => _ufle12jhs77_f_var2 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var3;
	public static BansheeGz.BGDatabase.BGFieldString _f_var3 => _ufle12jhs77_f_var3 ?? (_ufle12jhs77_f_var3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5298749018744724459UL, 8418088488485393283UL), () => _ufle12jhs77_f_var3 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var4;
	public static BansheeGz.BGDatabase.BGFieldString _f_var4 => _ufle12jhs77_f_var4 ?? (_ufle12jhs77_f_var4 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5505721170596384871UL, 16451685514435806388UL), () => _ufle12jhs77_f_var4 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var5;
	public static BansheeGz.BGDatabase.BGFieldString _f_var5 => _ufle12jhs77_f_var5 ?? (_ufle12jhs77_f_var5 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5284206983347084841UL, 2527899493376989596UL), () => _ufle12jhs77_f_var5 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_subUrl;
	public static BansheeGz.BGDatabase.BGFieldString _f_subUrl => _ufle12jhs77_f_subUrl ?? (_ufle12jhs77_f_subUrl = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5242019950426763846UL, 14299741865064188335UL), () => _ufle12jhs77_f_subUrl = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_isGroupTask;
	public static BansheeGz.BGDatabase.BGFieldBool _f_isGroupTask => _ufle12jhs77_f_isGroupTask ?? (_ufle12jhs77_f_isGroupTask = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5671408288324111920UL, 227898059225040027UL), () => _ufle12jhs77_f_isGroupTask = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_GroupTaskID;
	public static BansheeGz.BGDatabase.BGFieldString _f_GroupTaskID => _ufle12jhs77_f_GroupTaskID ?? (_ufle12jhs77_f_GroupTaskID = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5323515453101024486UL, 8155264044283532443UL), () => _ufle12jhs77_f_GroupTaskID = null));
	private BG_D3_UIField() : base(MetaDefault) {}
	private BG_D3_UIField(BGId id) : base(MetaDefault, id) {}
	private BG_D3_UIField(BGMetaEntity meta) : base(meta) {}
	private BG_D3_UIField(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static BG_D3_UIField FindEntity(Predicate<BG_D3_UIField> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<BG_D3_UIField> FindEntities(Predicate<BG_D3_UIField> filter, List<BG_D3_UIField> result=null, Comparison<BG_D3_UIField> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BG_D3_UIField> action, Predicate<BG_D3_UIField> filter=null, Comparison<BG_D3_UIField> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static BG_D3_UIField GetEntity(BGId entityId) => (BG_D3_UIField) MetaDefault.GetEntity(entityId);
	public static BG_D3_UIField GetEntity(int index) => (BG_D3_UIField) MetaDefault[index];
	public static BG_D3_UIField GetEntity(string entityName) => (BG_D3_UIField) MetaDefault.GetEntity(entityName);
	public static BG_D3_UIField NewEntity() => (BG_D3_UIField) MetaDefault.NewEntity();
	public static BG_D3_UIField NewEntity(BGId entityId) => (BG_D3_UIField) MetaDefault.NewEntity(entityId);
	public static BG_D3_UIField NewEntity(Action<BG_D3_UIField> callback) => (BG_D3_UIField) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BG_D3_UIField)entity)));
	public static BG_D3_UIField NewEntity(BG_D3_MPCValve_AASTable owner) => (BG_D3_UIField) MetaDefault.NewEntity(owner);
	public static BG_D3_UIField NewEntity(BG_D3_MPCValve_AASTable owner, BGId entityId) => (BG_D3_UIField) MetaDefault.NewEntity(owner, entityId);
	public static BG_D3_UIField NewEntity(BG_D3_MPCValve_AASTable owner, Action<BG_D3_UIField> callback) => (BG_D3_UIField) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((BG_D3_UIField)entity)));

	[Preserve]
	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_D3_UIField(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_D3_UIField(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "D3_UIField";
		public const string name = "name";
		public const string parent = "parent";
		public const string var1 = "var1";
		public const string var2 = "var2";
		public const string var3 = "var3";
		public const string var4 = "var4";
		public const string var5 = "var5";
		public const string subUrl = "subUrl";
		public const string isGroupTask = "isGroupTask";
		public const string GroupTaskID = "GroupTaskID";
	}
}

[Preserve]
public partial class BG_D3_MachField : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5284156965288738366UL,9506287178494351496UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public BG_D3_MPCValve_AASTable f_parent
	{
		get => (BG_D3_MPCValve_AASTable) _f_parent[Index];
		set => _f_parent[Index] = value;
	}
	public System.String f_var1
	{
		get => _f_var1[Index];
		set => _f_var1[Index] = value;
	}
	public System.String f_var2
	{
		get => _f_var2[Index];
		set => _f_var2[Index] = value;
	}
	public UnityEngine.Sprite f_img1 => _f_img1[Index];
	public UnityEngine.Sprite f_img2 => _f_img2[Index];
	public System.String f_suburl => _f_suburl[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5548375624791177935UL, 17776543140314935190UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_parent;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_parent => _ufle12jhs77_f_parent ?? (_ufle12jhs77_f_parent = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4854982715531286889UL, 12578672950775910046UL), () => _ufle12jhs77_f_parent = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var1;
	public static BansheeGz.BGDatabase.BGFieldString _f_var1 => _ufle12jhs77_f_var1 ?? (_ufle12jhs77_f_var1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4776468338246511765UL, 9600961108702612658UL), () => _ufle12jhs77_f_var1 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var2;
	public static BansheeGz.BGDatabase.BGFieldString _f_var2 => _ufle12jhs77_f_var2 ?? (_ufle12jhs77_f_var2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4858719606966106813UL, 11162521075278504342UL), () => _ufle12jhs77_f_var2 = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_f_img1;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _f_img1 => _ufle12jhs77_f_img1 ?? (_ufle12jhs77_f_img1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5234574012770630674UL, 7624818509558154884UL), () => _ufle12jhs77_f_img1 = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_f_img2;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _f_img2 => _ufle12jhs77_f_img2 ?? (_ufle12jhs77_f_img2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(4721438825493032831UL, 13771258142837073290UL), () => _ufle12jhs77_f_img2 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_suburl;
	public static BansheeGz.BGDatabase.BGFieldString _f_suburl => _ufle12jhs77_f_suburl ?? (_ufle12jhs77_f_suburl = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5679548890283991102UL, 17382299026485404045UL), () => _ufle12jhs77_f_suburl = null));
	private BG_D3_MachField() : base(MetaDefault) {}
	private BG_D3_MachField(BGId id) : base(MetaDefault, id) {}
	private BG_D3_MachField(BGMetaEntity meta) : base(meta) {}
	private BG_D3_MachField(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static BG_D3_MachField FindEntity(Predicate<BG_D3_MachField> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<BG_D3_MachField> FindEntities(Predicate<BG_D3_MachField> filter, List<BG_D3_MachField> result=null, Comparison<BG_D3_MachField> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BG_D3_MachField> action, Predicate<BG_D3_MachField> filter=null, Comparison<BG_D3_MachField> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static BG_D3_MachField GetEntity(BGId entityId) => (BG_D3_MachField) MetaDefault.GetEntity(entityId);
	public static BG_D3_MachField GetEntity(int index) => (BG_D3_MachField) MetaDefault[index];
	public static BG_D3_MachField GetEntity(string entityName) => (BG_D3_MachField) MetaDefault.GetEntity(entityName);
	public static BG_D3_MachField NewEntity() => (BG_D3_MachField) MetaDefault.NewEntity();
	public static BG_D3_MachField NewEntity(BGId entityId) => (BG_D3_MachField) MetaDefault.NewEntity(entityId);
	public static BG_D3_MachField NewEntity(Action<BG_D3_MachField> callback) => (BG_D3_MachField) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BG_D3_MachField)entity)));
	public UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<UnityEngine.Sprite>? Loadf_img1Async(Action<UnityEngine.Sprite> completedCallback) => BGAddressablesCodeGenUtils.LoadAsync(_f_img1, Index, completedCallback);
	public string Getf_img1AddressablesAddress() => _f_img1.GetAddressablesAddress(Index);
	public UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<UnityEngine.Sprite>? Loadf_img2Async(Action<UnityEngine.Sprite> completedCallback) => BGAddressablesCodeGenUtils.LoadAsync(_f_img2, Index, completedCallback);
	public string Getf_img2AddressablesAddress() => _f_img2.GetAddressablesAddress(Index);
	public static BG_D3_MachField NewEntity(BG_D3_MPCValve_AASTable owner) => (BG_D3_MachField) MetaDefault.NewEntity(owner);
	public static BG_D3_MachField NewEntity(BG_D3_MPCValve_AASTable owner, BGId entityId) => (BG_D3_MachField) MetaDefault.NewEntity(owner, entityId);
	public static BG_D3_MachField NewEntity(BG_D3_MPCValve_AASTable owner, Action<BG_D3_MachField> callback) => (BG_D3_MachField) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((BG_D3_MachField)entity)));

	[Preserve]
	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_D3_MachField(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_D3_MachField(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "D3_MachField";
		public const string name = "name";
		public const string parent = "parent";
		public const string var1 = "var1";
		public const string var2 = "var2";
		public const string img1 = "img1";
		public const string img2 = "img2";
		public const string suburl = "suburl";
	}
}

[Preserve]
public partial class BG_D2_MPCCooler_AASTable : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5699267538128754500UL,15896343137371279539UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_id
	{
		get => _f_id[Index];
		set => _f_id[Index] = value;
	}
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public System.String f_subname
	{
		get => _f_subname[Index];
		set => _f_subname[Index] = value;
	}
	public System.String f_requestUrl => _f_requestUrl[Index];
	public List<BG_D2_UIField> f_response => BGCodeGenUtils.GetNested<BG_D2_UIField>(_f_response, Index);
	/**<summary><![CDATA[
	실 AAS 주소
	]]></summary>*/
	public System.String f_machineUrl
	{
		get => _f_machineUrl[Index];
		set => _f_machineUrl[Index] = value;
	}
	public List<BG_D2_MachField> f_machine => BGCodeGenUtils.GetNested<BG_D2_MachField>(_f_machine, Index);
	/**<summary><![CDATA[
	mainAreaSO
	]]></summary>*/
	public UnityEngine.ScriptableObject f_mainSO => _f_mainSO[Index];
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_id;
	public static BansheeGz.BGDatabase.BGFieldString _f_id => _ufle12jhs77_f_id ?? (_ufle12jhs77_f_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4790707952816093648UL, 7744627132517999244UL), () => _ufle12jhs77_f_id = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5030805057289475200UL, 7727016058468062635UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_subname;
	public static BansheeGz.BGDatabase.BGFieldString _f_subname => _ufle12jhs77_f_subname ?? (_ufle12jhs77_f_subname = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5306232227420188996UL, 15149578668262285203UL), () => _ufle12jhs77_f_subname = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_requestUrl;
	public static BansheeGz.BGDatabase.BGFieldString _f_requestUrl => _ufle12jhs77_f_requestUrl ?? (_ufle12jhs77_f_requestUrl = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5512991431424660694UL, 1847579089062532244UL), () => _ufle12jhs77_f_requestUrl = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_response;
	public static BansheeGz.BGDatabase.BGFieldNested _f_response => _ufle12jhs77_f_response ?? (_ufle12jhs77_f_response = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5568981010991616145UL, 13288892159724521407UL), () => _ufle12jhs77_f_response = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_machineUrl;
	public static BansheeGz.BGDatabase.BGFieldString _f_machineUrl => _ufle12jhs77_f_machineUrl ?? (_ufle12jhs77_f_machineUrl = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4969583820680851152UL, 17743191217538663310UL), () => _ufle12jhs77_f_machineUrl = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_machine;
	public static BansheeGz.BGDatabase.BGFieldNested _f_machine => _ufle12jhs77_f_machine ?? (_ufle12jhs77_f_machine = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5545651388350691135UL, 13364537250806461371UL), () => _ufle12jhs77_f_machine = null));
	private static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _ufle12jhs77_f_mainSO;
	public static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _f_mainSO => _ufle12jhs77_f_mainSO ?? (_ufle12jhs77_f_mainSO = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityScriptableObject>(MetaDefault, new BGId(4639393013577195572UL, 18138661593549538733UL), () => _ufle12jhs77_f_mainSO = null));
	private BG_D2_MPCCooler_AASTable() : base(MetaDefault) {}
	private BG_D2_MPCCooler_AASTable(BGId id) : base(MetaDefault, id) {}
	private BG_D2_MPCCooler_AASTable(BGMetaEntity meta) : base(meta) {}
	private BG_D2_MPCCooler_AASTable(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static BG_D2_MPCCooler_AASTable FindEntity(Predicate<BG_D2_MPCCooler_AASTable> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<BG_D2_MPCCooler_AASTable> FindEntities(Predicate<BG_D2_MPCCooler_AASTable> filter, List<BG_D2_MPCCooler_AASTable> result=null, Comparison<BG_D2_MPCCooler_AASTable> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BG_D2_MPCCooler_AASTable> action, Predicate<BG_D2_MPCCooler_AASTable> filter=null, Comparison<BG_D2_MPCCooler_AASTable> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static BG_D2_MPCCooler_AASTable GetEntity(BGId entityId) => (BG_D2_MPCCooler_AASTable) MetaDefault.GetEntity(entityId);
	public static BG_D2_MPCCooler_AASTable GetEntity(int index) => (BG_D2_MPCCooler_AASTable) MetaDefault[index];
	public static BG_D2_MPCCooler_AASTable GetEntity(string entityName) => (BG_D2_MPCCooler_AASTable) MetaDefault.GetEntity(entityName);
	public static BG_D2_MPCCooler_AASTable NewEntity() => (BG_D2_MPCCooler_AASTable) MetaDefault.NewEntity();
	public static BG_D2_MPCCooler_AASTable NewEntity(BGId entityId) => (BG_D2_MPCCooler_AASTable) MetaDefault.NewEntity(entityId);
	public static BG_D2_MPCCooler_AASTable NewEntity(Action<BG_D2_MPCCooler_AASTable> callback) => (BG_D2_MPCCooler_AASTable) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BG_D2_MPCCooler_AASTable)entity)));
	public List<BG_D2_UIField> Fillf_response(List<BG_D2_UIField> result) => BGCodeGenUtils.GetNested<BG_D2_UIField>(_f_response, Index, result);
	public List<BG_D2_MachField> Fillf_machine(List<BG_D2_MachField> result) => BGCodeGenUtils.GetNested<BG_D2_MachField>(_f_machine, Index, result);
	public UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<UnityEngine.ScriptableObject>? Loadf_mainSOAsync(Action<UnityEngine.ScriptableObject> completedCallback) => BGAddressablesCodeGenUtils.LoadAsync(_f_mainSO, Index, completedCallback);
	public string Getf_mainSOAddressablesAddress() => _f_mainSO.GetAddressablesAddress(Index);

	[Preserve]
	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_D2_MPCCooler_AASTable(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_D2_MPCCooler_AASTable(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "D2_MPCCooler_AASTable";
		public const string id = "id";
		public const string name = "name";
		public const string subname = "subname";
		public const string requestUrl = "requestUrl";
		public const string response = "response";
		public const string machineUrl = "machineUrl";
		public const string machine = "machine";
		public const string mainSO = "mainSO";
	}
}

[Preserve]
public partial class BG_D2_UIField : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5693611880327077065UL,290243075152031150UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public BG_D2_MPCCooler_AASTable f_parent
	{
		get => (BG_D2_MPCCooler_AASTable) _f_parent[Index];
		set => _f_parent[Index] = value;
	}
	public System.String f_var1
	{
		get => _f_var1[Index];
		set => _f_var1[Index] = value;
	}
	public System.String f_var2
	{
		get => _f_var2[Index];
		set => _f_var2[Index] = value;
	}
	public System.String f_var3
	{
		get => _f_var3[Index];
		set => _f_var3[Index] = value;
	}
	public System.String f_var4
	{
		get => _f_var4[Index];
		set => _f_var4[Index] = value;
	}
	public System.String f_var5
	{
		get => _f_var5[Index];
		set => _f_var5[Index] = value;
	}
	/**<summary><![CDATA[
	WebView 용도
	]]></summary>*/
	public System.String f_subUrl
	{
		get => _f_subUrl[Index];
		set => _f_subUrl[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4937511330270419279UL, 4784784277100095650UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_parent;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_parent => _ufle12jhs77_f_parent ?? (_ufle12jhs77_f_parent = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5252419394873723999UL, 1245161000164235193UL), () => _ufle12jhs77_f_parent = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var1;
	public static BansheeGz.BGDatabase.BGFieldString _f_var1 => _ufle12jhs77_f_var1 ?? (_ufle12jhs77_f_var1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5722302337156205286UL, 4284751770110151090UL), () => _ufle12jhs77_f_var1 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var2;
	public static BansheeGz.BGDatabase.BGFieldString _f_var2 => _ufle12jhs77_f_var2 ?? (_ufle12jhs77_f_var2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5174110535494470844UL, 11301929163807077520UL), () => _ufle12jhs77_f_var2 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var3;
	public static BansheeGz.BGDatabase.BGFieldString _f_var3 => _ufle12jhs77_f_var3 ?? (_ufle12jhs77_f_var3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4954073035091853464UL, 4180205114641703327UL), () => _ufle12jhs77_f_var3 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var4;
	public static BansheeGz.BGDatabase.BGFieldString _f_var4 => _ufle12jhs77_f_var4 ?? (_ufle12jhs77_f_var4 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5344169840193674225UL, 13791416142970685614UL), () => _ufle12jhs77_f_var4 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var5;
	public static BansheeGz.BGDatabase.BGFieldString _f_var5 => _ufle12jhs77_f_var5 ?? (_ufle12jhs77_f_var5 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5210664884781780073UL, 17490282675780369544UL), () => _ufle12jhs77_f_var5 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_subUrl;
	public static BansheeGz.BGDatabase.BGFieldString _f_subUrl => _ufle12jhs77_f_subUrl ?? (_ufle12jhs77_f_subUrl = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4953088868892683093UL, 15375016580640931207UL), () => _ufle12jhs77_f_subUrl = null));
	private BG_D2_UIField() : base(MetaDefault) {}
	private BG_D2_UIField(BGId id) : base(MetaDefault, id) {}
	private BG_D2_UIField(BGMetaEntity meta) : base(meta) {}
	private BG_D2_UIField(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static BG_D2_UIField FindEntity(Predicate<BG_D2_UIField> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<BG_D2_UIField> FindEntities(Predicate<BG_D2_UIField> filter, List<BG_D2_UIField> result=null, Comparison<BG_D2_UIField> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BG_D2_UIField> action, Predicate<BG_D2_UIField> filter=null, Comparison<BG_D2_UIField> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static BG_D2_UIField GetEntity(BGId entityId) => (BG_D2_UIField) MetaDefault.GetEntity(entityId);
	public static BG_D2_UIField GetEntity(int index) => (BG_D2_UIField) MetaDefault[index];
	public static BG_D2_UIField GetEntity(string entityName) => (BG_D2_UIField) MetaDefault.GetEntity(entityName);
	public static BG_D2_UIField NewEntity() => (BG_D2_UIField) MetaDefault.NewEntity();
	public static BG_D2_UIField NewEntity(BGId entityId) => (BG_D2_UIField) MetaDefault.NewEntity(entityId);
	public static BG_D2_UIField NewEntity(Action<BG_D2_UIField> callback) => (BG_D2_UIField) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BG_D2_UIField)entity)));
	public static BG_D2_UIField NewEntity(BG_D2_MPCCooler_AASTable owner) => (BG_D2_UIField) MetaDefault.NewEntity(owner);
	public static BG_D2_UIField NewEntity(BG_D2_MPCCooler_AASTable owner, BGId entityId) => (BG_D2_UIField) MetaDefault.NewEntity(owner, entityId);
	public static BG_D2_UIField NewEntity(BG_D2_MPCCooler_AASTable owner, Action<BG_D2_UIField> callback) => (BG_D2_UIField) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((BG_D2_UIField)entity)));

	[Preserve]
	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_D2_UIField(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_D2_UIField(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "D2_UIField";
		public const string name = "name";
		public const string parent = "parent";
		public const string var1 = "var1";
		public const string var2 = "var2";
		public const string var3 = "var3";
		public const string var4 = "var4";
		public const string var5 = "var5";
		public const string subUrl = "subUrl";
	}
}

[Preserve]
public partial class BG_D2_MachField : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5577784677301476378UL,16383542669225377156UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public BG_D2_MPCCooler_AASTable f_parent
	{
		get => (BG_D2_MPCCooler_AASTable) _f_parent[Index];
		set => _f_parent[Index] = value;
	}
	public System.String f_var1
	{
		get => _f_var1[Index];
		set => _f_var1[Index] = value;
	}
	public System.String f_var2
	{
		get => _f_var2[Index];
		set => _f_var2[Index] = value;
	}
	public UnityEngine.Sprite f_img1 => _f_img1[Index];
	public UnityEngine.Sprite f_img2 => _f_img2[Index];
	public System.String f_suburl
	{
		get => _f_suburl[Index];
		set => _f_suburl[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5587804429194966246UL, 2161500541618162060UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_parent;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_parent => _ufle12jhs77_f_parent ?? (_ufle12jhs77_f_parent = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5553603966058852461UL, 12569212983080243344UL), () => _ufle12jhs77_f_parent = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var1;
	public static BansheeGz.BGDatabase.BGFieldString _f_var1 => _ufle12jhs77_f_var1 ?? (_ufle12jhs77_f_var1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4807576838018651215UL, 15611287913876288649UL), () => _ufle12jhs77_f_var1 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_var2;
	public static BansheeGz.BGDatabase.BGFieldString _f_var2 => _ufle12jhs77_f_var2 ?? (_ufle12jhs77_f_var2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5735371024277459995UL, 8680324151367149720UL), () => _ufle12jhs77_f_var2 = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_f_img1;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _f_img1 => _ufle12jhs77_f_img1 ?? (_ufle12jhs77_f_img1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5363920127793794538UL, 9036993564652362670UL), () => _ufle12jhs77_f_img1 = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_f_img2;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _f_img2 => _ufle12jhs77_f_img2 ?? (_ufle12jhs77_f_img2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(4717163250681443369UL, 8867978415065458074UL), () => _ufle12jhs77_f_img2 = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_suburl;
	public static BansheeGz.BGDatabase.BGFieldString _f_suburl => _ufle12jhs77_f_suburl ?? (_ufle12jhs77_f_suburl = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5690653639568007334UL, 4769118170318818489UL), () => _ufle12jhs77_f_suburl = null));
	private BG_D2_MachField() : base(MetaDefault) {}
	private BG_D2_MachField(BGId id) : base(MetaDefault, id) {}
	private BG_D2_MachField(BGMetaEntity meta) : base(meta) {}
	private BG_D2_MachField(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static BG_D2_MachField FindEntity(Predicate<BG_D2_MachField> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<BG_D2_MachField> FindEntities(Predicate<BG_D2_MachField> filter, List<BG_D2_MachField> result=null, Comparison<BG_D2_MachField> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BG_D2_MachField> action, Predicate<BG_D2_MachField> filter=null, Comparison<BG_D2_MachField> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static BG_D2_MachField GetEntity(BGId entityId) => (BG_D2_MachField) MetaDefault.GetEntity(entityId);
	public static BG_D2_MachField GetEntity(int index) => (BG_D2_MachField) MetaDefault[index];
	public static BG_D2_MachField GetEntity(string entityName) => (BG_D2_MachField) MetaDefault.GetEntity(entityName);
	public static BG_D2_MachField NewEntity() => (BG_D2_MachField) MetaDefault.NewEntity();
	public static BG_D2_MachField NewEntity(BGId entityId) => (BG_D2_MachField) MetaDefault.NewEntity(entityId);
	public static BG_D2_MachField NewEntity(Action<BG_D2_MachField> callback) => (BG_D2_MachField) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BG_D2_MachField)entity)));
	public UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<UnityEngine.Sprite>? Loadf_img1Async(Action<UnityEngine.Sprite> completedCallback) => BGAddressablesCodeGenUtils.LoadAsync(_f_img1, Index, completedCallback);
	public string Getf_img1AddressablesAddress() => _f_img1.GetAddressablesAddress(Index);
	public UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<UnityEngine.Sprite>? Loadf_img2Async(Action<UnityEngine.Sprite> completedCallback) => BGAddressablesCodeGenUtils.LoadAsync(_f_img2, Index, completedCallback);
	public string Getf_img2AddressablesAddress() => _f_img2.GetAddressablesAddress(Index);
	public static BG_D2_MachField NewEntity(BG_D2_MPCCooler_AASTable owner) => (BG_D2_MachField) MetaDefault.NewEntity(owner);
	public static BG_D2_MachField NewEntity(BG_D2_MPCCooler_AASTable owner, BGId entityId) => (BG_D2_MachField) MetaDefault.NewEntity(owner, entityId);
	public static BG_D2_MachField NewEntity(BG_D2_MPCCooler_AASTable owner, Action<BG_D2_MachField> callback) => (BG_D2_MachField) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((BG_D2_MachField)entity)));

	[Preserve]
	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BG_D2_MachField(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BG_D2_MachField(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "D2_MachField";
		public const string name = "name";
		public const string parent = "parent";
		public const string var1 = "var1";
		public const string var2 = "var2";
		public const string img1 = "img1";
		public const string img2 = "img2";
		public const string suburl = "suburl";
	}
}
#pragma warning restore 414
